### PR TITLE
[fix] alias logic

### PR DESCRIPTION
**Pull request by jkroso**
was having problems with `require('dep/file')`

### CODE REVIEW

**Comment by tj** [comment]
"reaching in" to a module like that is generally bad practice in node-land, IMO public api should be exposed via the main module

**Comment by jkroso** [comment]
I far prefer it so its a shame if it is considered bad practice. mind you I think of it as a package of modules rather than a module itself. I put them together because they make sense to maintain together more than I I think they make sense to use together.

**Comment by stagas** [comment]
regardless of the purpose, I think the fix looks good. If it happens to support dep/file as a side-effect then let it be.

**Comment by jkroso** [comment]
I actually wish more people structured their packages this way. Keeping similar stuff together is good for everyone. Would [jkroso/tree-each](//github.com/jkroso/tree-each) be better in any way as three separate repositories?

**Comment by jkroso** [comment]
actually tj was suggesting an object but whats the difference between an object an a directory anyway. Its just syntax in this context

**Comment by tj** [comment]
it promotes people reaching into other things that they shouldn't touch, people do this with connect for example all the time, but things breaks because I move or remove files and then they complain. You can still separate similar things such as css-parse / css-stringify and bring them together in a module like https://github.com/visionmedia/css

**Comment by jkroso** [comment]
personally I wouldn't be more, or less likely to rename a file compared to an object key but I should document my API better. BTW I wouldn't encourage `require('dep/lib/file')`, public files should obviously be at the top.

**Pull request merged**
