### PR TITLE
Change require.register signature and fix `require('toString')`

### PR DESCRIPTION
**Pull request by paulmillr**
1. `require.register` sig was changed from `module, exports, require` to `exports, require, module` to match node.js and other implementations.
2. Fixed bugs like `require('toString')`, `require('hasOwnProperty')`.

In IE<=8 the bug will still exist, but more global check will require a lot more code. This will slightly encourage people to upgrade.

### CODE REVIEW

**Comment by paulmillr** [comment]
needs tests, wip

**Comment by tj** [comment]
instead of going the Object.create(null) route we could just add a hasOwnProperty check

**Comment by paulmillr** [comment]
@visionmedia six checks

```
  return require.modules[reg] && reg
    || require.modules[regJSON] && regJSON
    || require.modules[index] && index
    || require.modules[indexJSON] && indexJSON
    || require.modules[orig] && orig
    || require.aliases[index];
```

**Comment by tj** [comment]
@paulmillr yeah true, probably not a big deal though since it does something like 100,000 ops/s at least and even a large app like ours probably only has ~700 requires at boot so a pretty small one time cost

**Comment by paulmillr** [comment]
@visionmedia changed `object.null` to has-prop, added tests etc.

**Comment by tj** [comment]
looks good but stylistic changes should be separate, I'll merge

**Pull request merged**
